import { ADMIN_SEARCH_MAX_LENGTH, BOT_TEXTS_APPLIED_WITHIN_S } from '@binarius/shared';

// Everything the admin pages say. Russian, per the project's language convention.

export const TEXTS = {
  loginTitle: 'Вход в админку',
  loginHeading: 'Вход сотрудника',
  loginField: 'Логин',
  passwordField: 'Пароль',
  loginSubmit: 'Войти',

  confirmTitle: 'Подтверждение входа',
  confirmHeading: 'Подтвердите вход',
  confirmHint: 'Нажмите «Подтвердить вход» в Telegram и введите код из сообщения.',
  codeField: 'Код из Telegram',
  confirmSubmit: 'Продолжить',

  sessionsTitle: 'Активные сессии',
  sessionsHeading: 'Активные сессии сотрудников',
  sessionsEmpty: 'Активных сессий нет.',
  columnLogin: 'Логин',
  columnName: 'Имя',
  columnIp: 'Адрес',
  columnUserAgent: 'Браузер',
  columnCreatedAt: 'Вход',
  columnLastSeenAt: 'Активность',
  columnExpiresAt: 'Истекает',
  columnAction: '',
  currentSession: 'текущая',
  revokeSubmit: 'Завершить',
  logoutSubmit: 'Выйти',
  noDisplayName: '—',

  navOverview: 'Сводка',
  navUsers: 'Пользователи',
  navSessions: 'Сессии сотрудников',
  navIntents: 'Заявки',
  navTradingSessions: 'Торговые сессии',
  navTokens: 'Токены',
  navAudit: 'Аудит',
  navBotTexts: 'Тексты бота',
  navLabel: 'Разделы админки',

  overviewTitle: 'Сводка',
  overviewHeading: 'Сводка',
  overviewUsers: 'Пользователи',
  overviewUsersTotal: 'Всего',
  overviewUsersToday: 'Новых сегодня',
  overviewUsersBlocked: 'Заблокированы',
  overviewUsersWithActiveAccount: 'С активным брокерским аккаунтом',
  overviewUsersActiveNow: 'Активны сейчас',
  overviewActiveNowHint: (minutes: number) =>
    `Пользователи, чья запись менялась за последние ${minutes} мин. — приблизительно, не факт присутствия в боте.`,
  overviewIntents: 'Сделки',
  overviewIntentsTotal: 'Всего',
  overviewIntentsToday: 'Сегодня',
  overviewIntentsByStatus: 'По статусам',
  overviewIntentsActive: 'Активные (не в конечном статусе)',
  overviewDayStartsAt: '«Сегодня» — с',
  overviewAsOf: 'Данные на',

  usersTitle: 'Пользователи',
  usersHeading: 'Пользователи',
  usersSearchField: 'Telegram ID, email или ID у брокера',
  usersSearchSubmit: 'Найти',
  usersSearchHint: 'Только точное совпадение.',
  usersEmpty: 'Пользователей нет.',
  usersNext: 'Далее',
  usersFirst: 'В начало',
  badSearch: `Запрос не подходит: до ${ADMIN_SEARCH_MAX_LENGTH} символов, без управляющих символов`,
  columnTelegramId: 'Telegram ID',
  columnStatus: 'Статус',
  columnTokens: 'Токены',
  columnUserCreatedAt: 'Создан',
  columnUpdatedAt: 'Обновлён',

  userTitle: 'Пользователь',
  userMain: 'Основное',
  userTokens: 'Токены',
  userBrokerAccounts: 'Брокерские аккаунты',
  userNoAccounts: 'Аккаунтов нет.',
  fieldId: 'ID',
  fieldLanguage: 'Язык',
  fieldAcquisitionSource: 'Источник',
  fieldAcquiredAt: 'Пришёл по источнику',
  fieldTelegramBlockedAt: 'Бот недоступен с',
  fieldNotificationLevel: 'Уведомления',
  fieldDemoStake: 'Демо-ставка',
  demoStakeDefault: 'минимальная ставка брокера',
  fieldBalance: 'Баланс',
  fieldReserved: 'В резерве',
  fieldAvailable: 'Доступно',
  columnBrokerUserId: 'ID у брокера',
  columnEmail: 'Email',
  columnPartner: 'Партнёрский',
  columnAuthRevokedReason: 'Причина отзыва',
  columnTradingHalted: 'Торговля остановлена',
  columnHaltedReason: 'Причина остановки',
  columnTokenExpiresAt: 'Токен до',
  columnTokenRotatedAt: 'Токен обновлён',
  yes: 'да',
  no: 'нет',
  none: '—',
  userStatus: { active: 'активен', blocked: 'заблокирован' },
  accountStatus: { pending: 'ожидает подтверждения', active: 'активен', revoked: 'отозван' },
  notificationLevel: { all: 'все', reduced: 'сокращённые', off: 'выключены' },
  userNotFoundTitle: 'Пользователь не найден',
  userNotFoundBody: 'Такого пользователя нет.',
  userTrading: 'Торговля',
  userIntentsCounts: (total: number, active: number) =>
    `Всего заявок: ${total}, активных: ${active}`,
  userIntentsRecent: (n: number) => `Последние ${n}`,
  userIntentsAll: 'Все заявки →',

  intentsTitle: 'Заявки',
  intentsHeading: 'Заявки',
  intentsFilterStatus: 'Статус',
  intentsFilterMode: 'Режим',
  intentsFilterUser: 'ID пользователя',
  intentsFilterSession: 'ID торговой сессии',
  intentsFilterAny: 'любой',
  intentsActive: 'активные',
  intentsFilterSubmit: 'Показать',
  intentsFilterHint:
    'Только точное совпадение. «Активные» — все статусы, кроме settled и rejected.',
  intentsEmpty: 'Заявок нет.',
  intentsNext: 'Далее',
  intentsFirst: 'В начало',
  intentsOfSession: 'Заявки этой сессии →',
  badFilter: 'Фильтр не подходит: статус и режим — из списка, ID — в формате UUID',
  columnIntentId: 'ID заявки',
  columnMode: 'Режим',
  columnDirection: 'Направление',
  columnAmount: 'Сумма',
  columnAsset: 'Актив',
  columnDuration: 'Длительность, с',
  columnLastError: 'Ошибка',
  intentTitle: 'Заявка',
  fieldUserId: 'ID пользователя',
  fieldBrokerAccountId: 'ID брокерского аккаунта',
  fieldTradingSessionId: 'ID торговой сессии',
  fieldClientRequestId: 'ID запроса клиента',
  fieldVersion: 'Версия',
  fieldTokensReserved: 'Токенов в резерве',
  fieldTransport: 'Транспорт',
  fieldSubmittedAt: 'Отправлена брокеру',
  fieldReconcileClaimedAt: 'Последняя сверка',
  intentNotFoundTitle: 'Заявка не найдена',
  intentNotFoundBody: 'Такой заявки нет.',

  tradingSessionsTitle: 'Торговые сессии',
  tradingSessionsHeading: 'Торговые сессии',
  tradingSessionsEmpty: 'Торговых сессий нет.',
  tradingSessionsNext: 'Далее',
  tradingSessionsFirst: 'В начало',
  tradingSessionIntents: 'Заявки →',
  columnSessionId: 'ID сессии',
  columnStopReason: 'Причина остановки',
  columnTrades: 'Сделок',
  columnStake: 'Ставка',
  columnStartedAt: 'Начата',
  columnEndedAt: 'Завершена',
  columnLastDecisionAt: 'Последнее решение',

  tokensTitle: 'Движения токенов',
  tokensHeading: 'Движения токенов',
  tokensFilterKind: 'Вид',
  tokensFilterUser: 'ID пользователя',
  tokensFilterAny: 'любой',
  tokensFilterSubmit: 'Показать',
  tokensFilterHint: 'Только точное совпадение.',
  tokensEmpty: 'Движений нет.',
  tokensNext: 'Далее',
  tokensFirst: 'В начало',
  tokensBadFilter: 'Фильтр не подходит: вид — из списка, ID пользователя — в формате UUID',
  columnLedgerAt: 'Время',
  columnKind: 'Вид',
  columnBalanceDelta: 'Баланс ±',
  columnReservedDelta: 'Резерв ±',
  columnReference: 'Основание',
  columnNote: 'Комментарий',
  userLedger: 'Движения токенов',
  userLedgerRecent: (n: number) => `Последние ${n}`,
  userLedgerAll: 'Все записи →',

  auditTitle: 'Журнал аудита',
  auditHeading: 'Журнал аудита',
  auditFilterAction: 'Действие',
  auditFilterEntityType: 'Тип сущности',
  auditFilterEntityId: 'ID сущности',
  auditFilterFrom: 'С даты (UTC)',
  auditFilterTo: 'По дату (UTC)',
  auditFilterAnyAction: 'любое',
  auditFilterAnyEntityType: 'любой',
  auditFilterSubmit: 'Показать',
  auditFilterHint:
    'Даты — сутки по UTC, обе границы включительно. Каждый запрос этой страницы сам записывается в журнал (audit_log_viewed).',
  auditActorFilter: (id: string) => `Сотрудник: ${id}`,
  auditActorReset: 'сбросить',
  auditActorAll: 'все события →',
  auditEmpty: 'Записей нет.',
  auditNext: 'Далее',
  auditFirst: 'В начало',
  auditBadFilter:
    'Фильтр не подходит: действие и тип — из списка, ID — в формате UUID, даты — ГГГГ-ММ-ДД, «с даты» не позже «по дату»',
  auditPayloadTruncated: '(обрезано)',
  columnAuditAt: 'Время',
  columnActor: 'Кто',
  columnAuditAction: 'Действие',
  columnEntity: 'Сущность',
  columnPayload: 'Данные',
  userAudit: 'Аудит',
  userAuditAll: 'Все события по пользователю →',

  passwordTitle: 'Смена пароля',
  passwordHeading: 'Сменить пароль',
  passwordLink: 'Сменить пароль',
  currentPasswordField: 'Текущий пароль',
  newPasswordField: 'Новый пароль',
  newPasswordRepeatField: 'Новый пароль ещё раз',
  passwordSubmit: 'Сменить пароль',
  passwordRevokesOthers: (n: number) =>
    `При смене пароля будут завершены другие открытые сессии: ${n}`,
  noOtherSessions: 'Других открытых сессий нет.',
  passwordChanged: (n: number) => `Пароль изменён. Завершено других сессий: ${n}`,
  passwordMismatch: 'Новые пароли не совпадают',
  passwordSameAsCurrent: 'Новый пароль совпадает с текущим',
  invalidCurrentPassword: 'Неверный текущий пароль',
  outcomeUnknownTitle: 'Результат неизвестен',
  outcomeUnknownBody:
    'Не удалось подтвердить результат. Пароль мог измениться — проверьте, войдя заново.',

  botTextsTitle: 'Тексты бота',
  botTextsHeading: 'Тексты клиентского бота',
  columnBotTextKey: 'Ключ',
  columnBotTextDescription: 'Где показывается',
  columnBotTextState: 'Состояние',
  botTextDefault: 'исходный',
  botTextChanged: (version: number, login: string | null) =>
    `изменён: версия ${version}, ${login ?? 'CLI'},`,
  botTextRejected: (reason: string) => `Не действует — ${reason}. Показан исходный текст.`,
  botTextReadOnly: 'Только чтение: команды и профиль бота пока нельзя править из админки',
  botTextOrphansHeading: 'Строки без ключа в каталоге',
  botTextOrphansHint: 'Ключа нет в каталоге этой версии — строка не действует.',
  columnBotTextVersion: 'Версия',
  botTextDelete: 'Удалить',
  botTextsNotice: {
    removed: 'Строка удалена.',
    gone: 'Строки уже нет.',
    changed: 'Строку успели изменить — проверьте версию и повторите.',
  },
  botTextNotice: {
    saved: `Сохранено. Бот применит текст в течение ${BOT_TEXTS_APPLIED_WITHIN_S} с`,
    reset: `Исходный текст возвращён. Бот применит его в течение ${BOT_TEXTS_APPLIED_WITHIN_S} с`,
    already_default: 'Текст уже исходный.',
    unchanged: 'Текст не изменился — сохранять нечего.',
  },
  botTextNotFoundTitle: 'Текст не найден',
  botTextNotFoundBody: 'Такого ключа нет в каталоге текстов.',
  botTextSourceField: 'Текст',
  botTextPreviewSubmit: 'Предпросмотр',
  botTextSaveSubmit: 'Сохранить',
  botTextResetSubmit: 'Вернуть исходный',
  botTextDefaultSource: 'Исходный текст',
  botTextSameAsDefault: 'Совпадает с исходным — «Вернуть исходный» снимет переопределение.',
  botTextConflict: (version: number) =>
    version === 0
      ? 'Текст уже изменил другой сотрудник: вернул исходный. Ниже — текущий текст, ваш черновик остался в поле; «Сохранить» ещё раз перезапишет текущий.'
      : `Текст уже изменил другой сотрудник (версия ${version}). Ниже — текущий текст, ваш черновик остался в поле; «Сохранить» ещё раз перезапишет текущий.`,
  botTextCurrent: 'Текущий текст',
  botTextPreviewHeading: 'Предпросмотр',
  botTextPreviewHint: 'Подстановки — образцы, фрагменты — действующие тексты.',
  botTextPlaceholders: 'Плейсхолдеры',
  botTextArg: (name: string, sample: string) =>
    `{${name}} — обязателен; в предпросмотре: ${sample}`,
  botTextFragmentChanged: '(изменён)',
  botTextNoPlaceholders: 'Плейсхолдеров нет.',
  botTextLimit: (limit: number, singleLine: boolean) =>
    `Лимит: ${limit} символов${singleLine ? ', одна строка' : ''}.`,
  botTextUsedIn: 'Используется в:',
  botTextOutcomeUnknown:
    'Не удалось подтвердить результат. Текст мог сохраниться — откройте его заново и проверьте версию.',

  invalidCredentials: 'Неверный логин или пароль',
  tooManyAttempts: 'Слишком много попыток. Подождите и попробуйте снова',
  tooManyCodeAttempts: 'Слишком много попыток. Подождите минуту',
  telegramUnavailable: 'Подтверждение через Telegram сейчас недоступно, вход невозможен',
  invalidCode: 'Неверный код',
  awaitingTelegram: 'Сначала нажмите кнопку в Telegram',
  expiredChallenge: 'Подтверждение истекло, войдите снова',
  badRequest: 'Проверьте введённые данные',

  forbiddenTitle: 'Запрос отклонён',
  forbiddenBody: 'Запрос пришёл не с этой страницы.',
  notFoundTitle: 'Страница не найдена',
  notFoundBody: 'Такой страницы нет.',
  errorTitle: 'Внутренняя ошибка',
  errorBody: 'Что-то пошло не так. Попробуйте позже.',
} as const;
