import { ADMIN_SEARCH_MAX_LENGTH } from '@binarius/shared';

// Everything the admin pages say. Russian, per the project's language convention.

export const TEXTS = {
  loginTitle: 'Вход в админку',
  loginHeading: 'Вход сотрудника',
  loginField: 'Логин',
  passwordField: 'Пароль',
  loginSubmit: 'Войти',

  confirmTitle: 'Подтверждение входа',
  confirmHeading: 'Подтвердите вход',
  confirmHint: 'Нажмите «Подтвердить вход» в Telegram и введите код из сообщения.',
  codeField: 'Код из Telegram',
  confirmSubmit: 'Продолжить',

  sessionsTitle: 'Активные сессии',
  sessionsHeading: 'Активные сессии сотрудников',
  sessionsEmpty: 'Активных сессий нет.',
  columnLogin: 'Логин',
  columnName: 'Имя',
  columnIp: 'Адрес',
  columnUserAgent: 'Браузер',
  columnCreatedAt: 'Вход',
  columnLastSeenAt: 'Активность',
  columnExpiresAt: 'Истекает',
  columnAction: '',
  currentSession: 'текущая',
  revokeSubmit: 'Завершить',
  logoutSubmit: 'Выйти',
  noDisplayName: '—',

  navOverview: 'Сводка',
  navUsers: 'Пользователи',
  navSessions: 'Сессии сотрудников',
  navIntents: 'Заявки',
  navTradingSessions: 'Торговые сессии',
  navTokens: 'Токены',
  navLabel: 'Разделы админки',

  overviewTitle: 'Сводка',
  overviewHeading: 'Сводка',
  overviewUsers: 'Пользователи',
  overviewUsersTotal: 'Всего',
  overviewUsersToday: 'Новых сегодня',
  overviewUsersBlocked: 'Заблокированы',
  overviewUsersWithActiveAccount: 'С активным брокерским аккаунтом',
  overviewUsersActiveNow: 'Активны сейчас',
  overviewActiveNowHint: (minutes: number) =>
    `Пользователи, чья запись менялась за последние ${minutes} мин. — приблизительно, не факт присутствия в боте.`,
  overviewIntents: 'Сделки',
  overviewIntentsTotal: 'Всего',
  overviewIntentsToday: 'Сегодня',
  overviewIntentsByStatus: 'По статусам',
  overviewIntentsActive: 'Активные (не в конечном статусе)',
  overviewDayStartsAt: '«Сегодня» — с',
  overviewAsOf: 'Данные на',

  usersTitle: 'Пользователи',
  usersHeading: 'Пользователи',
  usersSearchField: 'Telegram ID, email или ID у брокера',
  usersSearchSubmit: 'Найти',
  usersSearchHint: 'Только точное совпадение.',
  usersEmpty: 'Пользователей нет.',
  usersNext: 'Далее',
  usersFirst: 'В начало',
  badSearch: `Запрос не подходит: до ${ADMIN_SEARCH_MAX_LENGTH} символов, без управляющих символов`,
  columnTelegramId: 'Telegram ID',
  columnStatus: 'Статус',
  columnTokens: 'Токены',
  columnUserCreatedAt: 'Создан',
  columnUpdatedAt: 'Обновлён',

  userTitle: 'Пользователь',
  userMain: 'Основное',
  userTokens: 'Токены',
  userBrokerAccounts: 'Брокерские аккаунты',
  userNoAccounts: 'Аккаунтов нет.',
  fieldId: 'ID',
  fieldLanguage: 'Язык',
  fieldAcquisitionSource: 'Источник',
  fieldAcquiredAt: 'Пришёл по источнику',
  fieldTelegramBlockedAt: 'Бот недоступен с',
  fieldNotificationLevel: 'Уведомления',
  fieldDemoStake: 'Демо-ставка',
  demoStakeDefault: 'минимальная ставка брокера',
  fieldBalance: 'Баланс',
  fieldReserved: 'В резерве',
  fieldAvailable: 'Доступно',
  columnBrokerUserId: 'ID у брокера',
  columnEmail: 'Email',
  columnPartner: 'Партнёрский',
  columnAuthRevokedReason: 'Причина отзыва',
  columnTradingHalted: 'Торговля остановлена',
  columnHaltedReason: 'Причина остановки',
  columnTokenExpiresAt: 'Токен до',
  columnTokenRotatedAt: 'Токен обновлён',
  yes: 'да',
  no: 'нет',
  none: '—',
  userStatus: { active: 'активен', blocked: 'заблокирован' },
  accountStatus: { pending: 'ожидает подтверждения', active: 'активен', revoked: 'отозван' },
  notificationLevel: { all: 'все', reduced: 'сокращённые', off: 'выключены' },
  userNotFoundTitle: 'Пользователь не найден',
  userNotFoundBody: 'Такого пользователя нет.',
  userTrading: 'Торговля',
  userIntentsCounts: (total: number, active: number) =>
    `Всего заявок: ${total}, активных: ${active}`,
  userIntentsRecent: (n: number) => `Последние ${n}`,
  userIntentsAll: 'Все заявки →',

  intentsTitle: 'Заявки',
  intentsHeading: 'Заявки',
  intentsFilterStatus: 'Статус',
  intentsFilterMode: 'Режим',
  intentsFilterUser: 'ID пользователя',
  intentsFilterSession: 'ID торговой сессии',
  intentsFilterAny: 'любой',
  intentsActive: 'активные',
  intentsFilterSubmit: 'Показать',
  intentsFilterHint:
    'Только точное совпадение. «Активные» — все статусы, кроме settled и rejected.',
  intentsEmpty: 'Заявок нет.',
  intentsNext: 'Далее',
  intentsFirst: 'В начало',
  intentsOfSession: 'Заявки этой сессии →',
  badFilter: 'Фильтр не подходит: статус и режим — из списка, ID — в формате UUID',
  columnIntentId: 'ID заявки',
  columnMode: 'Режим',
  columnDirection: 'Направление',
  columnAmount: 'Сумма',
  columnAsset: 'Актив',
  columnDuration: 'Длительность, с',
  columnLastError: 'Ошибка',
  intentTitle: 'Заявка',
  fieldUserId: 'ID пользователя',
  fieldBrokerAccountId: 'ID брокерского аккаунта',
  fieldTradingSessionId: 'ID торговой сессии',
  fieldClientRequestId: 'ID запроса клиента',
  fieldVersion: 'Версия',
  fieldTokensReserved: 'Токенов в резерве',
  fieldTransport: 'Транспорт',
  fieldSubmittedAt: 'Отправлена брокеру',
  fieldReconcileClaimedAt: 'Последняя сверка',
  intentNotFoundTitle: 'Заявка не найдена',
  intentNotFoundBody: 'Такой заявки нет.',

  tradingSessionsTitle: 'Торговые сессии',
  tradingSessionsHeading: 'Торговые сессии',
  tradingSessionsEmpty: 'Торговых сессий нет.',
  tradingSessionsNext: 'Далее',
  tradingSessionsFirst: 'В начало',
  tradingSessionIntents: 'Заявки →',
  columnSessionId: 'ID сессии',
  columnStopReason: 'Причина остановки',
  columnTrades: 'Сделок',
  columnStake: 'Ставка',
  columnStartedAt: 'Начата',
  columnEndedAt: 'Завершена',
  columnLastDecisionAt: 'Последнее решение',

  tokensTitle: 'Движения токенов',
  tokensHeading: 'Движения токенов',
  tokensFilterKind: 'Вид',
  tokensFilterUser: 'ID пользователя',
  tokensFilterAny: 'любой',
  tokensFilterSubmit: 'Показать',
  tokensFilterHint: 'Только точное совпадение.',
  tokensEmpty: 'Движений нет.',
  tokensNext: 'Далее',
  tokensFirst: 'В начало',
  tokensBadFilter: 'Фильтр не подходит: вид — из списка, ID пользователя — в формате UUID',
  columnLedgerAt: 'Время',
  columnKind: 'Вид',
  columnBalanceDelta: 'Баланс ±',
  columnReservedDelta: 'Резерв ±',
  columnReference: 'Основание',
  columnNote: 'Комментарий',
  userLedger: 'Движения токенов',
  userLedgerRecent: (n: number) => `Последние ${n}`,
  userLedgerAll: 'Все записи →',

  invalidCredentials: 'Неверный логин или пароль',
  tooManyAttempts: 'Слишком много попыток. Подождите и попробуйте снова',
  tooManyCodeAttempts: 'Слишком много попыток. Подождите минуту',
  telegramUnavailable: 'Подтверждение через Telegram сейчас недоступно, вход невозможен',
  invalidCode: 'Неверный код',
  awaitingTelegram: 'Сначала нажмите кнопку в Telegram',
  expiredChallenge: 'Подтверждение истекло, войдите снова',
  badRequest: 'Проверьте введённые данные',

  forbiddenTitle: 'Запрос отклонён',
  forbiddenBody: 'Запрос пришёл не с этой страницы.',
  notFoundTitle: 'Страница не найдена',
  notFoundBody: 'Такой страницы нет.',
  errorTitle: 'Внутренняя ошибка',
  errorBody: 'Что-то пошло не так. Попробуйте позже.',
} as const;
